export const ADMIN_VIEW_REQUEST = "ADMIN_VIEW_REQUEST";
export const ADMIN_VIEW_SUCCESS = "ADMIN_VIEW_SUCCESS";
export const ADMIN_FEATURE_REQUEST = "ADMIN_FEARURE_REQUEST";
export const ADMIN_FEATURE_SUCCESS = "ADMIN_FEARURE_SUCCESS";
export const ADMIN_PERMISSION_REQUEST = "ADMIN_PERMISSION_REQUEST";
export const ADMIN_PERMISSION_SUCCESS = "ADMIN_PERMISSION_SUCCESS";
export const ADMIN_ROLEGET_REQUEST = "ADMIN_ROLEGET_REQUEST";
export const ADMIN_ROLEGET_SUCCESS = "ADMIN_ROLEGET_SUCCESS";
export const ADMIN_ROLEPOST_REQUEST = "ADMIN_ROLEPOST_REQUEST";
export const ADMIN_ROLEPOST_SUCCESS = "ADMIN_ROLEPOST_SUCCESS";
export const ADMIN_ROLEUPDATE_REQUEST = "ADMIN_ROLEUPDATE_REQUEST";
export const ADMIN_ROLEUPDATE_SUCCESS = "ADMIN_ROLEUPDATE_SUCCESS";
export const ADMIN_ROLEDELETE_REQUEST = "ADMIN_ROLEDELETE_REQUEST";
export const ADMIN_ROLEDELETE_SUCCESS = "ADMIN_ROLEDELETE_SUCCESS";
export const ADMIN_MANAGEUSER_GETREQUEST = "ADMIN_MANAGEUSER_GETREQUEST";
export const ADMIN_MANAGEUSER_GETSUCCESS = "ADMIN_MANAGEUSER_GETSUCCESS";
export const ADMIN_MANAGEUSER_POSTREQUEST = "ADMIN_MANAGEUSER_POSTREQUEST";
export const ADMIN_MANAGEUSER_POSTSUCCESS = "ADMIN_MANAGEUSER_POSTSUCCESS";
export const ADMIN_MANAGEUSER_SINGLEUSERREQUEST =
  "ADMIN_MANAGEUSER_SINGLEUSERREQUEST";
export const ADMIN_MANAGEUSER_SINGLEUSERSUCCESS =
  "ADMIN_MANAGEUSER_SINGLEUSERSUCCESS";
export const ADMIN_MANAGEUSER_DELETEREQUEST = "ADMIN_MANAGEUSER_DELETEREQUEST";
export const ADMIN_MANAGEUSER_DELETESUCCESS = "ADMIN_MANAGEUSER_DELETESUCCESS";
export const MANAGE_COMPONENTS_REQUEST = "MANAGE_COMPONENTS_REQUEST";
export const MANAGE_COMPONENTS_SUCCESS = "MANAGE_COMPONENTS_SUCCESS";
export const ADMIN_MANAGECOMPONENTS_POSTREQUEST =
  "ADMIN_MANAGECOMPONENTS_POSTREQUEST";
export const ADMIN_MANAGECOMPONENTS_POSTSUCCESS =
  "ADMIN_MANAGECOMPONENTS_POSTSUCCESS";
export const ADMIN_MANAGECOMPONENTS_GETVIEWREQUEST =
  "ADMIN_MANAGECOMPONENTS_GETVIEWREQUEST";
export const ADMIN_MANAGECOMPONENTS_GETVIEWSUCCESS =
  "ADMIN_MANAGECOMPONENTS_GETVIEWSUCCESS";
export const ADMIN_MANAGECOMPONENTS_POSTEDIT_REQUEST =
  "ADMIN_MANAGECOMPONENTS_POSTEDIT_REQUEST";
export const ADMIN_MANAGECOMPONENTS_POSTEDIT_SUCCESS =
  "ADMIN_MANAGECOMPONENTS_POSTEDIT_SUCCESS";
export const ADMIN_TAGLIST_REQUEST = "ADMIN_TAGLIST_REQUEST";
export const ADMIN_TAGLIST_SUCCESS = "ADMIN_TAGLIST_SUCCESS";
export const ADMIN_GET_FIELDS_DATA_REQUEST = "ADMIN_GET_FIELDS_DATA_REQUEST";
export const ADMIN_GET_FIELDS_DATA_SUCCESS = "ADMIN_GET_FIELDS_DATA_SUCCESS";
export const ADMIN_MANAGEUSER_UPDATEREQUEST = "ADMIN_MANAGEUSER_UPDATEREQUEST";
export const ADMIN_MANAGEUSER_UPDATESUCCESS = "ADMIN_MANAGEUSER_UPDATESUCCESS";
export const ADMIN_TECHSTACKS_REQUEST = "ADMIN_TECHSTACKS_REQUEST";
export const ADMIN_TECHSTACKS_SUCCESS = "ADMIN_TECHSTACKS_SUCCESS";
export const ADMIN_COMPONENTS_REQUEST = "ADMIN_COMPONENTS_REQUEST";
export const ADMIN_COMPONENTS_SUCCESS = "ADMIN_COMPONENTS_SUCCESS";
export const ADMIN_FILES_REQUEST = "ADMIN_FILES_REQUEST";
export const ADMIN_FILES_SUCCESS = "ADMIN_FILES_SUCCESS";
export const ADMIN_COMPONENTSTATUS_POST_REQUEST =
  "ADMIN_COMPONENTSTATUS_POST_REQUEST";
export const ADMIN_COMPONENTSTATUS_POST_SUCCESS =
  "ADMIN_COMPONENTSTATUS_POST_SUCCESS";
export const ADMIN_TECHSTACKS_GET_REQUEST = "ADMIN_TECHSTACKS_GET_REQUEST";
export const ADMIN_TECHSTACKS_GET_SUCCESS = "ADMIN_TECHSTACKS_GET_SUCCESS";
export const ADMIN_TECHSTACKSAPPROVALREPORT_GET_REQUEST =
  "ADMIN_TECHSTACKSAPPROVALREPORT_GET_REQUEST";
export const ADMIN_TECHSTACKSAPPROVALREPORT_GET_SUCCESS =
  "ADMIN_TECHSTACKSAPPROVALREPORT_GET_SUCCESS";
export const TREDENSOFCOMPONENT_GET_REQUEST = "TREDENSOFCOMPONENT_GET_REQUEST";
export const TREDENSOFCOMPONENT_GET_SUCCESS = "TREDENSOFCOMPONENT_GET_SUCCESS";
